---
- hosts: dev
  become: True
  tasks:
  - name: ensure repository key is installed
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
 - name: ensure docker registry is available
     apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present
 - name: ensure docker and dependencies are installed
      apt: name=docker-ce update_cache=yes
  - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: hariapp
        image: "ashiwnik87/deployment-using-ansible-cm-tool:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
